/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RSA;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Mvami N. Jonalex
 */
public class KeyDetails extends javax.swing.JDialog {

    /**
     * Creates new form KeyDetails
     */
    //<editor-fold defaultstate="collapsed" desc="coonstructors">
    public KeyDetails(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        user = new CurrentUser();
        initComponents();
    }
    
    public KeyDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        user = new CurrentUser();
        initComponents();
    }
//</editor-fold>
    
    
    //<editor-fold defaultstate="collapsed" desc="set methods">
    public void setListInfo(String[] tmp){
        listInfo = tmp;
    }
//</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="gett methods">
    public String[] getListInfo(){
        return listInfo;
    }
//</editor-fold>
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PublicKeyTaa = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        PrivateKeyTaa = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ModulusTaa = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        SizeTaa = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Modify = new javax.swing.JButton();
        IdentifierTfd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Détails de la clé");
        setPreferredSize(new java.awt.Dimension(440, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Détails "));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 50));
        jLabel1.setText("Identifiant : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 50, 50));
        jLabel2.setText("Clé  public :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(50, 50, 50));
        jLabel3.setText("Clé privée :");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        PublicKeyTaa.setEditable(false);
        PublicKeyTaa.setColumns(20);
        PublicKeyTaa.setLineWrap(true);
        PublicKeyTaa.setRows(1);
        PublicKeyTaa.setWrapStyleWord(true);
        PublicKeyTaa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PublicKeyTaa.setDragEnabled(true);
        jScrollPane1.setViewportView(PublicKeyTaa);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setAutoscrolls(true);

        PrivateKeyTaa.setEditable(false);
        PrivateKeyTaa.setColumns(20);
        PrivateKeyTaa.setLineWrap(true);
        PrivateKeyTaa.setRows(1);
        PrivateKeyTaa.setWrapStyleWord(true);
        PrivateKeyTaa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PrivateKeyTaa.setDragEnabled(true);
        PrivateKeyTaa.setInheritsPopupMenu(true);
        jScrollPane5.setViewportView(PrivateKeyTaa);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);

        ModulusTaa.setEditable(false);
        ModulusTaa.setColumns(20);
        ModulusTaa.setLineWrap(true);
        ModulusTaa.setRows(1);
        ModulusTaa.setWrapStyleWord(true);
        ModulusTaa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ModulusTaa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ModulusTaa.setDragEnabled(true);
        jScrollPane3.setViewportView(ModulusTaa);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(50, 50, 50));
        jLabel5.setText("Module : ");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        SizeTaa.setEditable(false);
        SizeTaa.setColumns(20);
        SizeTaa.setRows(1);
        SizeTaa.setMinimumSize(new java.awt.Dimension(4, 24));
        SizeTaa.setPreferredSize(new java.awt.Dimension(164, 24));
        jScrollPane6.setViewportView(SizeTaa);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 50, 50));
        jLabel4.setText("Size : ");

        Modify.setText("Modifier");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });
        Modify.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ModifyKeyReleased(evt);
            }
        });

        IdentifierTfd.setEditable(false);
        IdentifierTfd.setBackground(new java.awt.Color(255, 255, 255));
        IdentifierTfd.setPreferredSize(new java.awt.Dimension(200, 22));
        IdentifierTfd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdentifierTfdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IdentifierTfd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Modify))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdentifierTfd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Modify, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
        editing = !editing;
        if(editing){
            oldIden = IdentifierTfd.getText();
            IdentifierTfd.setEditable(true);
            IdentifierTfd.setForeground(Color.black);
        }
        else{
            readKeys();
            modifyKey(oldIden);
            writeKeys();
            IdentifierTfd.setEditable(false);
            IdentifierTfd.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_ModifyActionPerformed

    private void IdentifierTfdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdentifierTfdKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10) ModifyKeyReleased(evt);
    }//GEN-LAST:event_IdentifierTfdKeyReleased

    private void ModifyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifyKeyReleased
        // TODO add your handling code here:
        editing = !editing;
        if(editing){
            oldIden = IdentifierTfd.getText();
            IdentifierTfd.setEditable(true);
            IdentifierTfd.setForeground(Color.black);
        }
        else{
            readKeys();
            modifyKey(oldIden);
            writeKeys();
            IdentifierTfd.setEditable(false);
            IdentifierTfd.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_ModifyKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KeyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KeyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KeyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KeyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                KeyDetails dialog = new KeyDetails(new javax.swing.JDialog(),true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    //<editor-fold defaultstate="collapsed" desc="prroperties">
    private String[] listInfo;

    
    private String oldIden;
    private ArrayList <String> KeysListArray;
    private boolean editing = false;
    
    private CurrentUser user;
//</editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdentifierTfd;
    private javax.swing.JButton Modify;
    private javax.swing.JTextArea ModulusTaa;
    private javax.swing.JTextArea PrivateKeyTaa;
    private javax.swing.JTextArea PublicKeyTaa;
    private javax.swing.JTextArea SizeTaa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    //<editor-fold defaultstate="collapsed" desc="methods">
    public void displayDetails(){
        IdentifierTfd.setText(listInfo[0]);
        IdentifierTfd.setForeground(Color.GRAY);
        SizeTaa.setText(listInfo[1]+"bits");
        PublicKeyTaa.setText("("+listInfo[2]+", "+listInfo[4]+")");
        if("-".equals(listInfo[3])){
            PrivateKeyTaa.setText("-");
        }
        else{
            PrivateKeyTaa.setText("("+listInfo[3]+", "+listInfo[4]+")");
        }
        ModulusTaa.setText(listInfo[4]);       
    }
    
    private void writeKeys() {
        Fichier f = new Fichier();
        // Open in write mode
        f.openInWrite("Data/Users/User_id"+user.getUserId()+"/Keys/Keys.txt");
        // Go through the array
        for (String elt : KeysListArray) {
            // Ecrire l'élément (contact) courant
            f.write(elt);
        }
        // Fermer le fichier
        f.closeFile();
    }
    
    private void readKeys() {
        KeysListArray = new ArrayList();
        Fichier f = new Fichier();
        // Open file in read mode
        f.openInRead("Data/Users/User_id"+user.getUserId()+"/Keys/Keys.txt");
        String readLine;
        // do ...
        do {
            // read line
            readLine = f.read();
            if (readLine != null){
                //Add read line to array list
                KeysListArray.add(readLine);
            }
            // ... while the read line is not null.
        } while (readLine != null);
        f.closeFile();
    }
    
    private void modifyKey(String oldIden) {
        String[] tmp = new String[5];
        int i = 0;
        
        for (String elt : KeysListArray) {
            tmp  = new Fichier().extractData(elt, ";");
            if(tmp[0].equals(oldIden)){
                KeysListArray.set(i, elt.replace(oldIden, IdentifierTfd.getText()));
                break;
            }
            i++;
        }
    }
//</editor-fold>
}
