/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RSA;

import java.math.BigInteger;
import java.util.ArrayList;

/**
 *
 * @author Mvami N. Jonalex
 */
public class KeyInsertion extends javax.swing.JDialog {

    /**
     * Creates new form KeyInsertion
     */
    public KeyInsertion(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ExpPrivateKeyTfd.setEnabled(false);
        EnableEntryCbx.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdentifierTfd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ExpPublicKeyTfd = new javax.swing.JTextField();
        ExpPrivateKeyTfd = new javax.swing.JTextField();
        ModulusTfd = new javax.swing.JTextField();
        ValidateBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        EnableEntryCbx = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 280));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), " Insérer une Clé "));

        jLabel4.setText("Clé privée :");

        jLabel3.setText("Clé publique : ");

        jLabel5.setText("Module :");

        IdentifierTfd.setForeground(new java.awt.Color(102, 102, 102));
        IdentifierTfd.setText("SecureId");

        jLabel2.setText("Describtion : ");

        ExpPublicKeyTfd.setForeground(new java.awt.Color(102, 102, 102));
        ExpPublicKeyTfd.setText("Exposant de la Clé publique ");
        ExpPublicKeyTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpPublicKeyTfdActionPerformed(evt);
            }
        });

        ExpPrivateKeyTfd.setForeground(new java.awt.Color(102, 102, 102));
        ExpPrivateKeyTfd.setText("Exposnt de la Clé privée");

        ModulusTfd.setForeground(new java.awt.Color(102, 102, 102));
        ModulusTfd.setText("Module");

        ValidateBtn.setText("Valider");
        ValidateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidateBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        EnableEntryCbx.setText(" ");
        EnableEntryCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableEntryCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdentifierTfd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpPublicKeyTfd, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(ExpPrivateKeyTfd)
                    .addComponent(ModulusTfd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnableEntryCbx)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValidateBtn)
                .addGap(18, 18, 18)
                .addComponent(CancelBtn)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IdentifierTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ExpPublicKeyTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ExpPrivateKeyTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnableEntryCbx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ModulusTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValidateBtn)
                    .addComponent(CancelBtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExpPublicKeyTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpPublicKeyTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpPublicKeyTfdActionPerformed

    private void ValidateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidateBtnActionPerformed
        // TODO add your handling code here:
        newKey[0] = IdentifierTfd.getText();
        newKey[1] = Integer.toString(new BigInteger(ModulusTfd.getText()).bitLength());
        newKey[2] = ExpPublicKeyTfd.getText();
        if(EnaEntry){
            newKey[3] = IdentifierTfd.getText();
        }
        else{
            newKey[3] = "-";
        }
        newKey[4] = ModulusTfd.getText();
        
        String newKeyLine = newKey[0]+";"+newKey[1]+";"+newKey[2]+";"+newKey[3]+";"+newKey[4];
        readKeys();
        KeysListArray.add(0, newKeyLine);
        writeKeys();

        dispose();
    }//GEN-LAST:event_ValidateBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void EnableEntryCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnableEntryCbxActionPerformed
        // TODO add your handling code here:
        EnaEntry = !EnaEntry;
        ExpPrivateKeyTfd.setEnabled(EnaEntry);
    }//GEN-LAST:event_EnableEntryCbxActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KeyInsertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KeyInsertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KeyInsertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KeyInsertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                KeyInsertion dialog = new KeyInsertion(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    private boolean EnaEntry = false;
    private String[] newKey = new String[5];
    private ArrayList <String> KeysListArray; 
    
    private CurrentUser user = new CurrentUser();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JCheckBox EnableEntryCbx;
    private javax.swing.JTextField ExpPrivateKeyTfd;
    private javax.swing.JTextField ExpPublicKeyTfd;
    private javax.swing.JTextField IdentifierTfd;
    private javax.swing.JTextField ModulusTfd;
    private javax.swing.JButton ValidateBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void writeKeys() {
        Fichier f = new Fichier();
      // Open in write mode
      f.openInWrite("Data/Users/User_id"+user.getUserId()+"/Keys/Keys.txt");
      // Go through the array
      for (String elt : KeysListArray) {
          // Ecrire l'élément (contact) courant
         f.write(elt);
      }
      // Fermer le fichier
      f.closeFile();
    }

    private void readKeys() {
        KeysListArray = new ArrayList();
        Fichier f = new Fichier();
        // Open file in read mode
        f.openInRead("Data/Users/User_id"+user.getUserId()+"/Keys/Keys.txt");
        String readLine;
        // do ...
        do {
            // read line
           readLine = f.read();
	   if (readLine != null){
               //Add read line to array list 
              KeysListArray.add(readLine);
            }
        // ... while the read line is not null.
        } while (readLine != null);
        f.closeFile();
    }
}
