/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RSA;

import java.awt.Color;

/**
 *
 * @author Mvami N. Jonalex
 */
public class RsaKey extends javax.swing.JPanel {

    /**
     * Creates new form RsaKey
     */
    
    private String[] listInfo;
    private int id;
    private boolean selected;
    
    public RsaKey(String[] info, int in) {
        setVisible(true);
        initComponents();
        setListInfo(info);
        setId(in);
        displayInfo();
        colorierIdPair();
        
    }
    
    public void setListInfo(String[] tmp){
        listInfo  = tmp;
    }
    
    public void setId(int tmp){
        id = tmp;
    }
    
    public void setSelected(boolean tmp){
        selected = tmp;
    }
    
    public String[] getListInfo(){
        return listInfo;
    }
    
    public int getId(){
        return id;
    }
    
    public boolean getSelected(){
        return  selected;
    }
    
    private void displayInfo(){
        IdentifierLbl.setText(listInfo[0]);
        SizeLbl.setText(listInfo[1]+"bits");  
    }
    
    private void setCouleur(javax.swing.JPanel tmp ){
                  tmp.setBackground(Color.WHITE);
                  tmp.setOpaque(true);
     }

    private void colorierIdPair(){
        // Si l'id du contact est pair
        if(id % 2 == 0){
            setCouleur(InfoPnl);
        }
    }
   
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoPnl = new javax.swing.JPanel();
        ChoosedCbx = new javax.swing.JCheckBox();
        IdentifierLbl = new javax.swing.JLabel();
        SizeLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(300, 25));

        InfoPnl.setPreferredSize(new java.awt.Dimension(300, 23));

        ChoosedCbx.setText(" ");
        ChoosedCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosedCbxActionPerformed(evt);
            }
        });

        IdentifierLbl.setText("RsaKey Identifier");
        IdentifierLbl.setPreferredSize(new java.awt.Dimension(83, 23));

        SizeLbl.setText("RsaKey Size");
        SizeLbl.setPreferredSize(new java.awt.Dimension(60, 23));

        javax.swing.GroupLayout InfoPnlLayout = new javax.swing.GroupLayout(InfoPnl);
        InfoPnl.setLayout(InfoPnlLayout);
        InfoPnlLayout.setHorizontalGroup(
            InfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChoosedCbx)
                .addGap(18, 18, 18)
                .addComponent(IdentifierLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        InfoPnlLayout.setVerticalGroup(
            InfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(InfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChoosedCbx)
                    .addComponent(IdentifierLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ChoosedCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosedCbxActionPerformed
        // TODO add your handling code here:
        if(!selected){
            setSelected(true);
        }
        else{
            setSelected(false);
        }
    }//GEN-LAST:event_ChoosedCbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChoosedCbx;
    private javax.swing.JLabel IdentifierLbl;
    private javax.swing.JPanel InfoPnl;
    private javax.swing.JLabel SizeLbl;
    // End of variables declaration//GEN-END:variables
}
